import { readFile, writeFile } from "node:fs/promises";

import popsData from "../data/index.js";

const declarationUrl = new URL("../main.d.ts", import.meta.url);
const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const unknownArgs = args.filter(arg => arg !== "--check");

if (unknownArgs.length > 0) {
  throw new Error(`Unknown argument(s): ${unknownArgs.join(", ")}`);
}

const providerKeys = Object.keys(popsData.providers).sort();
const iataCodes = [...popsData.iata.keys()].sort();

if (providerKeys.length === 0 || iataCodes.length === 0) {
  throw new Error("Provider and IATA key unions must not be empty");
}

const invalidProviderKeys = providerKeys.filter(key => !/^[a-z0-9]+$/.test(key));
const invalidIataCodes = iataCodes.filter(code => !/^[A-Z]{3}$/.test(code));

if (invalidProviderKeys.length > 0) {
  throw new Error(`Invalid provider key(s): ${invalidProviderKeys.join(", ")}`);
}

if (invalidIataCodes.length > 0) {
  throw new Error(`Invalid IATA code(s): ${invalidIataCodes.join(", ")}`);
}

const publicKeys = ["all", ...providerKeys, ...iataCodes];
if (new Set(publicKeys).size !== publicKeys.length) {
  throw new Error("Provider, IATA, and aggregate keys must not overlap");
}

const formatUnion = (name, values) => {
  const members = values.map(
    (value, index) => `  | ${JSON.stringify(value)}${index === values.length - 1 ? ";" : ""}`
  );

  return `export type ${name} =\n${members.join("\n")}`;
};

const declaration = `// Generated by \`bun run types:generate\`. Do not edit manually.

export type Coordinates = [latitude: number, longitude: number];

${formatUnion("ProviderKey", providerKeys)}

${formatUnion("IataCode", iataCodes)}

export interface AllPoPsEntry {
  code: IataCode[];
  geo: Coordinates[];
}

export interface ProviderPoPsEntry {
  code: IataCode[];
  geo: Coordinates[];
}

export interface LocationPoPsEntry {
  geo: Coordinates;
  providers: ProviderKey[];
}

export type PoPs = {
  all: AllPoPsEntry;
} & {
  [K in ProviderKey]: ProviderPoPsEntry;
} & {
  [K in IataCode]: LocationPoPsEntry;
};

declare const pops: PoPs;

export default pops;
`;

const currentDeclaration = await readFile(declarationUrl, "utf8").catch(error => {
  if (error.code === "ENOENT") return null;
  throw error;
});

if (checkOnly) {
  if (currentDeclaration !== declaration) {
    console.error("main.d.ts is out of date. Run `bun run types:generate`.");
    process.exitCode = 1;
  }
} else if (currentDeclaration !== declaration) {
  await writeFile(declarationUrl, declaration);
  console.log("Generated main.d.ts");
}
